apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: tls-issuer
  namespace: cert-manager
spec:
  acme:
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-tls-secret
              key: api-token